name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "**/setup.py"

      - name: Install Python dependencies
        run: pip install mako pygments requests

      - name: Run all testcases
        run: python3 -m unittest pyradium.tests

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Build the example presentation
        run: ./pyradium.py render -f -I examples/sub examples/example.xml -R rendered/customfiles:customfiles/ rendered -vvv
